mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^todo/', include('todo.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/todo/urls.py
from django.conf.urls import url
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
# Set the app name / namespace?
app_name = 'todo'

# Define this apps urls
urlpatterns = [
	# ex: /todo/
    url(r'^$', views.view_index, name='index'),
    # ex: /todo/list/5
    url(r'^new-list/$', views.view_new_list, name='new-list'),
    # ex: /todo/new-list
    url(r'^list/(?P<list_id>[0-9]+)/$', views.view_list, name='list'),
    # ex: /todo/delete-list/5
    url(r'^delete-list/(?P<list_id>[0-9]+)/$', views.view_delete_list, name='delete-list'),
    # ex: /todo/task/5
    url(r'^task/(?P<task_id>[0-9]+)/$', views.view_task, name='task'),
    # ex: /todo/new-task
    url(r'^new-task/(?P<list_id>[0-9]+)/$', views.view_new_task, name='new-task'),
    # ex: /todo/delete-task/5
    url(r'^delete-task/(?P<task_id>[0-9]+)/$', views.view_delete_task, name='delete-task'),
    # ex: /todo/login
    url(r'^login/$', auth_views.login, name='login'),
    # ex: /todo/logout
    url(r'^logout/$', auth_views.logout, name='logout'),
]

mysite/todo/models.py
from django.db import models

# List
class List(models.Model):
	name = models.CharField(max_length=200)
	date_published = models.DateTimeField('date published')

	# Override to string value
	def __str__(self):
		return self.name

	def was_published_recently(self):
		return self.date_published >= timezone.now() - datetime.timedelta(days=1)

# Task
class Task(models.Model):
	name = models.CharField(max_length=200)
	description = models.CharField(max_length=200)
	date_published = models.DateTimeField('date published')
	list = models.ForeignKey(List, on_delete=models.CASCADE)

	# Override to string value
	def __str__(self):
		return self.name

	def was_published_recently(self):
		return self.date_published >= timezone.now() - datetime.timedelta(days=1)

mysite/todo/forms.py
from django import forms

class TaskForm(forms.Form):
    name = forms.CharField(label='Name', max_length=200, widget=forms.TextInput(attrs={'class' : 'input'}))
    description = forms.CharField(label='Description', max_length=200, widget=forms.Textarea(attrs={'class' : 'textarea'}))

class ListForm(forms.Form):
    name = forms.CharField(label='Name', max_length=200, widget=forms.TextInput(attrs={'class' : 'input'}))

mysite/todo/views.py
# Imports
from django.http import HttpResponse
from django.template import loader
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from .models import Task, List
from .forms import TaskForm, ListForm
from .utils import set_response_message, get_request_message


""" 


Index 


"""
# Create your views here.
@login_required
@never_cache
def view_index(request, context = {}):
	""" Shows the index view which lists the lists """

	# Get the data
	context['lists'] = List.objects.order_by('-date_published')

	# Render and return
	template = loader.get_template('todo/index.html')
	return HttpResponse(template.render(context, request))

""" 


List 


"""
@login_required
@never_cache
def view_list(request, list_id, context = {}):
	""" Shows the list view """

	# Incase a message has been passed we need to load it in
	context = get_request_message(request, context)

	# Get the data
	list_object = get_object_or_404(List, pk=list_id)
	task_objects = list_object.task_set.all()

	context['list'] = list_object
	context['tasks'] = task_objects

	# Render and return
	template = loader.get_template('todo/list.html')
	return HttpResponse(template.render(context, request))

@login_required
@never_cache
def view_new_list(request, context = {}):
	""" Create a new task """

	# Incase a message has been passed we need to load it in
	context = get_request_message(request, context)

	# Set these up early so we can use them later
	form = None

	"""
	If the forms been submitted lets validate and try create a new list
	"""
	if request.method == 'POST':
		# Give the POST data to the form object
		form = ListForm(request.POST)
		if form.is_valid():

			# Form has validated, Lets create the object
			new_list = List.objects.create( name=request.POST.get("name"), date_published=timezone.now() )
			
			# Redirect with message
			print("setting list created thing")
			set_response_message(request, "List Created" )
			return redirect('todo:list', list_id = new_list.id )

		else:
			context['message'] = "Error creating List"

	else:
		form = ListForm()

	# Get the data
	context['form'] = form

	# Render and return
	template = loader.get_template('todo/new_list.html')
	return HttpResponse(template.render(context, request))

@login_required
@never_cache
def view_delete_list(request, list_id, context = {}):
	""" Delete a task and then redirect """

	# Incase a message has been passed we need to load it in
	context = get_request_message(request, context)

	list_object = get_object_or_404(List, pk=list_id)
	list_object.delete()

	# TODO make this a proper redirect
	set_response_message(request, "List Deleted" )
	return redirect('todo:index')

""" 


Task 


"""
@login_required
@never_cache
def view_task(request, task_id, context = {}):
	""" Shows the task view """
	
	# Incase a message has been passed we need to load it in
	context = get_request_message(request, context)

	# Set these up early so we can use them later
	task_object = get_object_or_404(Task, pk=task_id)
	form = None

	"""
	If the forms been submitted we're going to validate it and potentially save it
	"""
	if request.method == 'POST':
		# Give the POST data to the form object
		form = TaskForm(request.POST)
		if form.is_valid():
			task_object.name = request.POST.get("name")
			task_object.description = request.POST.get("description")
			task_object.save()

			# Redirect with message
			set_response_message(request, "Task Updated" )
			return redirect('todo:task', task_id = task_object.id )

		else:
			context['message'] = "Error updating Task"
	else:

		# Nothing has been posted, get the form as usual
		form = TaskForm(initial={ 'name': task_object.name, 'description':task_object.description })

	# Get the data
	context['task'] = task_object
	context['form'] = form
	context['list'] = task_object.list

	# Render and return
	template = loader.get_template('todo/task.html')
	return HttpResponse(template.render(context, request))

@login_required
@never_cache
def view_new_task(request, list_id, context = {}):
	""" Create a new task """

	# Incase a message has been passed we need to load it in
	context = get_request_message(request, context)

	# Set these up early so we can use them later
	list = get_object_or_404(List, pk=list_id)
	form = None

	"""
	If the forms been submitted lets validate and try create a new task
	"""
	if request.method == 'POST':
		# Give the POST data to the form object
		form = TaskForm(request.POST)
		if form.is_valid():

			# As the forms validated, lets create the object
			task_object = list.task_set.create(name=request.POST.get("name"), description=request.POST.get("description"), date_published=timezone.now() )
			
			# Redirect with message
			set_response_message(request, "Task Created" )
			return redirect('todo:task', task_id = task_object.id )
		else:
			
			context['message'] = "Error creating Task"

	else:
		form = TaskForm()

	# Get the data
	context['form'] = form
	context['list'] = list

	# Render and return
	template = loader.get_template('todo/new_task.html')
	return HttpResponse(template.render(context, request))

@login_required
@never_cache
def view_delete_task(request, task_id, context = {}):
	""" Delete a task and then redirect """

	task_object = get_object_or_404(Task, pk=task_id)
	list = List.objects.get(pk=task_object.list.id)
	task_object.delete()

	# Redirect with message
	set_response_message(request, "Task Deleted" )
	return redirect('todo:list', list_id = list.id )

mysite/todo/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block headtitle %}{% endblock %}</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.1/css/bulma.min.css">
	</head>
	<body>
		<section class="section" style="background-color:#e1e1e1;">
			<div class="container">
				<div class="columns">
					<div class="column is-2">
				  		<p class="title is-2">Todo</p>
					</div>
				  	<div class="column is-4">
						<h1 class="title is-4">{% block title %}{% endblock %}</h1>
						<p class="subtitle">{% block subtitle %}{% endblock %}</p>
					</div>
					<div class="column is-6 has-text-right">

						<div class="dropdown is-right is-hoverable">
							<div class="dropdown-trigger">
								<button class="button is-info" aria-haspopup="true" aria-controls="dropdown-menu6">
									<span>About this project</span>
									<span class="icon is-small">
										<i class="fa fa-angle-down" aria-hidden="true"></i>
									</span>
								</button>
							</div>
							<div class="dropdown-menu" id="dropdown-menu6" role="menu">
								<div class="dropdown-content">
									<div class="dropdown-item">
										<p>Written in the <strong>Django Framework</strong> and <strong>Bulma CSS Framework.</strong></p>
									</div>
  									<hr class="dropdown-divider">
									<div class="dropdown-item">
										<p>By Gareth Somers; it's my <strong>first project</strong> using those technologies.</strong></p>
									</div>
									<hr class="dropdown-divider">
									<div class="dropdown-item">
										<p>Its intention is to demonstrate my <strong>progression</strong> and <strong>adaptability</strong> as a developer.</strong></p>
									</div>
									<hr class="dropdown-divider">
									<div class="dropdown-item">
										<p>You can view the code on <a href="https://bitbucket.org/garethsomers/django-todo-list">bitbucket here</a></strong></p>
									</div>
								</div>
							</div>
						</div>

						{% if user.is_authenticated %}
			        		<a href="{% url 'todo:logout' %}" class="button is-warning"><span class="icon is-small"><i class="fa fa-sign-out"></i></span><span>Logout</span></a>    
					    {% endif %}

					</div>
				</div>
			</div>
		</section>
		<section class="section">
			<div class="container">

				{% if messages %}
				    {% for message in messages %}
				    	<div {% if message.tags %} class="notification is-info {{ message.tags }}"{% endif %}>{{ message }}</div>
				    {% endfor %}
				{% endif %}

				<div class="columns">
				  	<div class="column">
						<nav class="breadcrumb" aria-label="breadcrumbs">
							<ul>
								{% block breadcrumb %}{% endblock %}
							</ul>
						</nav>
					</div>
					<div class="column has-text-right">
						{% block buttons %}{% endblock %}
					</div>
				</div>

				{% block content %}{% endblock %}
				
			</div>
		</section>
	</body>
</html>

mysite/todo/templates/todo/index.html
{% extends "../base.html" %}


{% block headtitle %}Todo Lists{% endblock %}
{% block title %}Todo Lists{% endblock %}
{% block subtitle %}Welcome to my Todo List{% endblock %}


{% block breadcrumb %}
	<li class="is-active"><a href="{% url 'todo:index' %}" aria-current="page"><span class="icon is-small"><i class="fa fa-home"></i></span><span>Todo</span></a></li>
{% endblock %}

{% block buttons %}<a href="{% url 'todo:new-list' %}" class="button is-primary is-outlined"><span class="icon"><i class="fa fa-plus-square-o"></i></span><span class="is-hidden-mobile">New</span></a>{% endblock %}

{% block content %}
	<div class="content">

		{% if lists %}
		    <table class="table">
		    	<thead>
			    	<tr>
			    		<th>Name</th>
			    		<th>Task Count</th>
			    		<th class="is-hidden-mobile">Date</th>
			    		<th class="has-text-right">Actions</th>
			    	</tr>
			    </thead>
		    	<tbody>
				    {% for list in lists %}
				    	<tr>
					        <td><a href="/todo/list/{{ list.id }}/">{{ list.name }}</a></td>
					        <td>{{ list.task_set.count }}</td>
					        <td class="is-hidden-mobile">{{ list.date_published }}</td>
					        <td class="has-text-right"><a href="{% url 'todo:delete-list' list.id %}" class="button is-danger is-outlined"><span class="icon"><i class="fa fa-minus-square-o"></i></span><span class="is-hidden-mobile">Delete</span></a></td>
					    </tr>
				    {% endfor %}
				</tbody>
		    </table>
		{% else %}
		    <p>No lists are available.</p>
		{% endif %}
	</div>
{% endblock %}

mysite/todo/templates/todo/list.html
{% extends "../base.html" %}


{% block headtitle %}Viewing List: {{list.name}}{% endblock %}
{% block title %}Viewing List: {{list.name}}{% endblock %}
{% block subtitle %}Here are the list of tasks{% endblock %}


{% block breadcrumb %}
	<li><a href="{% url 'todo:index' %}"><span class="icon is-small"><i class="fa fa-home"></i></span><span>Todo</span></a></li>
	<li class="is-active"><a href="#" aria-current="page"><span class="icon is-small"><i class="fa fa-list"></i></span><span>{{ list.name }}</span></a></li>
{% endblock %}

{% block buttons %}<a href="{% url 'todo:new-task' list.id %}" class="button is-primary is-outlined"><span class="icon"><i class="fa fa-plus-square-o"></i></span><span class="is-hidden-mobile">New</span></a>{% endblock %}

{% block content %}
	<div class="content">	
		{% if tasks %}
		    <table class="table">
		    	<thead>
			    	<tr>
			    		<th>Name</th>
			    		<th>Task Count</th>
			    		<th class="is-hidden-mobile">Date</th>
			    		<th class="has-text-right">Actions</th>
			    	</tr>
			    </thead>
		    	<tbody>
				    {% for task in tasks %}
				    	<tr>
					        <td><a href="{% url 'todo:task' task.id %}">{{ task.name }}</a></td>
					        <td>{{ task.description }}</td>
					        <td class="is-hidden-mobile">{{ task.date_published }}</td>
					        <td class="has-text-right"><a href="{% url 'todo:delete-task' task.id %}" class="button is-danger is-outlined"><span class="icon"><i class="fa fa-minus-square-o"></i></span><span class="is-hidden-mobile">Delete</span></a></td>
					    </tr>
				    {% endfor %}
				</tbody>
		    </table>
		{% else %}
		    <p>No tasks are available.</p>
		{% endif %}

		<p><a href="{% url 'todo:index' %}">Return to Home</a></p>
	</div>
{% endblock %}

mysite/todo/templates/todo/new_list.html
{% extends "../base.html" %}

{% block headtitle %}New List{% endblock %}
{% block title %}New List{% endblock %}
{% block subtitle %}Once you create a list you can add tasks underneath it{% endblock %}

{% block breadcrumb %}
	<li><a href="{% url 'todo:index' %}"><span class="icon is-small"><i class="fa fa-home"></i></span><span>Todo</span></a></li>
	<li class="is-active"><a href="#" aria-current="page"><span class="icon is-small"><i class="fa fa-list"></i></span><span>{% block current_breadcrumb %}New Task{% endblock %}</span></a></li>
{% endblock %}

{% block content %}
	<div class="content">
		<div class="box">			
			<form method="post">
				{% csrf_token %}

				<!-- only used for new -->
				<input type="hidden" name"list_id" value="{{list.id}}" />
				{% block hidden_field %}{% endblock %}
				
				{% for field in form %}
					{% include "todo/parts/form-field.html" %}
				{% endfor %}

				<div class="field is-horizontal">
					<div class="field-label">
					<!-- Left empty for spacing -->
					</div>
					<div class="field-body">
						<div class="field">
							<div class="control">
								<button class="button is-primary" type="submit">Save</button>
							</div>
						</div>
					</div>
				</div>

			</form>
		</div>

		<p><a href="{% url 'todo:index' %}">Return to Home</a></p>
	</div>

{% endblock %}

mysite/todo/templates/todo/new_task.html
{% extends "../base.html" %}

{% block headtitle %}New Task{% endblock %}
{% block title %}New Task{% endblock %}
{% block subtitle %}From the list: "{{list.name}}{% endblock %}

{% block breadcrumb %}
	<li><a href="{% url 'todo:index' %}"><span class="icon is-small"><i class="fa fa-home"></i></span><span>Todo</span></a></li>
	<li><a href="{% url 'todo:list' list.id %}"><span class="icon is-small"><i class="fa fa-list"></i></span><span>{{ list.name }}</span></a></li>
	<li class="is-active"><a href="#" aria-current="page"><span class="icon is-small"><i class="fa fa-check"></i></span><span>{% block current_breadcrumb %}New Task{% endblock %}</span></a></li>
{% endblock %}

{% block content %}
	<div class="content">
		<div class="box">			
			<form method="post">
				{% csrf_token %}

				<!-- only used for new -->
				<input type="hidden" name"list_id" value="{{list.id}}" />
				{% block hidden_field %}{% endblock %}
				
				{% for field in form %}
					{% include "todo/parts/form-field.html" %}
				{% endfor %}

				<div class="field is-horizontal">
					<div class="field-label">
					<!-- Left empty for spacing -->
					</div>
					<div class="field-body">
						<div class="field">
							<div class="control">
								<button class="button is-primary" type="submit">Save</button>
							</div>
						</div>
					</div>
				</div>

			</form>
		</div>

		<p><a href="{% url 'todo:list' list.id %}">Return to List</a></p>
	</div>

{% endblock %}

mysite/todo/templates/todo/parts/form-field.html
<div class="field is-horizontal">
	<div class="field-label is-normal">
		{{ field.label_tag }}
	</div>
	<div class="field-body">
		<div class="field is-narrow">
			<div class="control">
				<div class="is-fullwidth">
					{{ field.errors }}
					{{ field }}
					{% if field.help_text %}
						<p class="help">{{ field.help_text|safe }}</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>

mysite/todo/templates/todo/task.html
{% extends "todo/new_task.html" %}

{% block headtitle %}Viewing Task: {{ task.name }}{% endblock %}
{% block title %}Viewing Task: {{ task.name }}{% endblock %}

{% block current_breadcrumb %}{{task.name}}{% endblock %}

{% block hidden_field %}<input type="hidden" name"task_id" value="{{task.id}}" />{% endblock %}